DATA:
  data_name: Mid360
  data_root: "" # Fill in the data path
  label_mapping: util/Mid.yaml
  classes: 14
  fea_dim: 6
  voxel_size: [0.1, 0.1, 0.1]
  voxel_max: 1200000

TRAIN:
  input_c: 3
  m: 32
  block_reps: 2
  layers: [32, 64, 128, 256, 256]
  focal_r: [ [ 3, 1, 1, 1 ],[ 3, 1, 1, 1 ],[ 3, 1, 1, 1 ],[ 3, 1, 1, 1 ],[ 3, 1, 1, 1 ] ]
  focal_th: [ [ 3, 1, 1, 1 ],[ 3, 1, 1, 1 ],[ 3, 1, 1, 1 ],[ 3, 1, 1, 1 ],[ 3, 1, 1, 1 ] ]
  focal_h: [ [ 3, 1, 1, 1 ],[ 3, 1, 1, 1 ],[ 3, 1, 1, 1 ],[ 3, 1, 1, 1 ],[ 3, 1, 1, 1 ] ]
  sync_bn: True
  drop_path_rate: 0.3
  max_batch_points: 25000000
  xyz_norm: False
  pc_range: [[-51.2, -51.2, -3], [51.2, 51.2, 15.0]]
  unet_layers: [1,2,3,4,5]
  grad_checkpoint_layers: []
  aug: True
  save_memory: True
  train_gpu: [0] # change your GPU#
  workers: 16
  batch_size: 1
  ignore_label: 255
  manual_seed: 123
  print_freq: 10
  save_freq: 1
  save_path: runs/Mid_record
  weight: # Fill in the weight path
  val: True
  use_tta: True
  vote_num: 4

Distributed:
  dist_url: tcp://127.0.0.1:6789
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0

